// <auto-generated />
using System;
using AquariumFishTracker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AquariumFishTracker.Migrations
{
    [DbContext(typeof(AquariumContext))]
    [Migration("20260222055753_RemoveHealthStatus")]
    partial class RemoveHealthStatus
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AquariumFishTracker.Models.Fish", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<double>("LengthCm")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TankId")
                        .HasColumnType("int");

                    b.Property<double>("WeightGrams")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("TankId");

                    b.ToTable("Fish");
                });

            modelBuilder.Entity("AquariumFishTracker.Models.Tank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Ammonia")
                        .HasColumnType("float");

                    b.Property<DateTime?>("LastCleanedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Nitrate")
                        .HasColumnType("float");

                    b.Property<double>("Nitrite")
                        .HasColumnType("float");

                    b.Property<double>("PH")
                        .HasColumnType("float");

                    b.Property<double>("TemperatureC")
                        .HasColumnType("float");

                    b.Property<double>("VolumeLiters")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Tanks");
                });

            modelBuilder.Entity("AquariumFishTracker.Models.Fish", b =>
                {
                    b.HasOne("AquariumFishTracker.Models.Tank", "Tank")
                        .WithMany("Fish")
                        .HasForeignKey("TankId");

                    b.Navigation("Tank");
                });

            modelBuilder.Entity("AquariumFishTracker.Models.Tank", b =>
                {
                    b.Navigation("Fish");
                });
#pragma warning restore 612, 618
        }
    }
}
